// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

type Generator_Expecter struct {
	mock *mock.Mock
}

func (_m *Generator) EXPECT() *Generator_Expecter {
	return &Generator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *Generator) Generate() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Generator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Generator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Generator_Expecter) Generate() *Generator_Generate_Call {
	return &Generator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *Generator_Generate_Call) Run(run func()) *Generator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generator_Generate_Call) Return(_a0 string) *Generator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Generator_Generate_Call) RunAndReturn(run func() string) *Generator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
