# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "folder_id" {
    type = string
    description = "Folder ID for resources to be created in"
    default = ""
}

variable "dns_domain" {
    type = string
    default = "iam.de1phin.ru"
}


