service:
  token_address: 0.0.0.0:8444
  swagger_address: 0.0.0.0:8445
  swagger_host: token.swagger.iam.de1phin.ru
  account_address: account-service:8443
  connection_timeout: 10s
  token_length: 64

expire:
  min_interval: 15s
  max_interval: 1m

postgres:
  host: rc1a-4s9kodv0e4g841m3.mdb.yandexcloud.net
  port: 6432
  user: token-service-user
  dbname: token-service

postgres_password_lockbox_secret_id: e6qav0q81e7am68ghadt
